version: 2
updates:
  - package-ecosystem: "npm"    
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
